<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\AdminMessage\OTAEvent instead.
     * @deprecated
     */
    class AdminMessage_OTAEvent {}
}
class_exists(AdminMessage\OTAEvent::class);
@trigger_error('Meshtastic\AdminMessage_OTAEvent is deprecated and will be removed in the next major release. Use Meshtastic\AdminMessage\OTAEvent instead', E_USER_DEPRECATED);

