<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\AdminMessage\BackupLocation instead.
     * @deprecated
     */
    class AdminMessage_BackupLocation {}
}
class_exists(AdminMessage\BackupLocation::class);
@trigger_error('Meshtastic\AdminMessage_BackupLocation is deprecated and will be removed in the next major release. Use Meshtastic\AdminMessage\BackupLocation instead', E_USER_DEPRECATED);

