<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\AdminMessage\ModuleConfigType instead.
     * @deprecated
     */
    class AdminMessage_ModuleConfigType {}
}
class_exists(AdminMessage\ModuleConfigType::class);
@trigger_error('Meshtastic\AdminMessage_ModuleConfigType is deprecated and will be removed in the next major release. Use Meshtastic\AdminMessage\ModuleConfigType instead', E_USER_DEPRECATED);

