<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\AdminMessage\InputEvent instead.
     * @deprecated
     */
    class AdminMessage_InputEvent {}
}
class_exists(AdminMessage\InputEvent::class);
@trigger_error('Meshtastic\AdminMessage_InputEvent is deprecated and will be removed in the next major release. Use Meshtastic\AdminMessage\InputEvent instead', E_USER_DEPRECATED);

