<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\AdminMessage\ConfigType instead.
     * @deprecated
     */
    class AdminMessage_ConfigType {}
}
class_exists(AdminMessage\ConfigType::class);
@trigger_error('Meshtastic\AdminMessage_ConfigType is deprecated and will be removed in the next major release. Use Meshtastic\AdminMessage\ConfigType instead', E_USER_DEPRECATED);

