<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/channel.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Channel\Role instead.
     * @deprecated
     */
    class Channel_Role {}
}
class_exists(Channel\Role::class);
@trigger_error('Meshtastic\Channel_Role is deprecated and will be removed in the next major release. Use Meshtastic\Channel\Role instead', E_USER_DEPRECATED);

