<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\SecurityConfig instead.
     * @deprecated
     */
    class Config_SecurityConfig {}
}
class_exists(Config\SecurityConfig::class);
@trigger_error('Meshtastic\Config_SecurityConfig is deprecated and will be removed in the next major release. Use Meshtastic\Config\SecurityConfig instead', E_USER_DEPRECATED);

