<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\PositionConfig instead.
     * @deprecated
     */
    class Config_PositionConfig {}
}
class_exists(Config\PositionConfig::class);
@trigger_error('Meshtastic\Config_PositionConfig is deprecated and will be removed in the next major release. Use Meshtastic\Config\PositionConfig instead', E_USER_DEPRECATED);

