<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\LoRaConfig instead.
     * @deprecated
     */
    class Config_LoRaConfig {}
}
class_exists(Config\LoRaConfig::class);
@trigger_error('Meshtastic\Config_LoRaConfig is deprecated and will be removed in the next major release. Use Meshtastic\Config\LoRaConfig instead', E_USER_DEPRECATED);

