<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\NetworkConfig\IpV4Config instead.
     * @deprecated
     */
    class Config_NetworkConfig_IpV4Config {}
}
class_exists(Config\NetworkConfig\IpV4Config::class);
@trigger_error('Meshtastic\Config_NetworkConfig_IpV4Config is deprecated and will be removed in the next major release. Use Meshtastic\Config\NetworkConfig\IpV4Config instead', E_USER_DEPRECATED);

