<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\BluetoothConfig instead.
     * @deprecated
     */
    class Config_BluetoothConfig {}
}
class_exists(Config\BluetoothConfig::class);
@trigger_error('Meshtastic\Config_BluetoothConfig is deprecated and will be removed in the next major release. Use Meshtastic\Config\BluetoothConfig instead', E_USER_DEPRECATED);

