<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\NetworkConfig\AddressMode instead.
     * @deprecated
     */
    class Config_NetworkConfig_AddressMode {}
}
class_exists(Config\NetworkConfig\AddressMode::class);
@trigger_error('Meshtastic\Config_NetworkConfig_AddressMode is deprecated and will be removed in the next major release. Use Meshtastic\Config\NetworkConfig\AddressMode instead', E_USER_DEPRECATED);

