<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\DeviceConfig\RebroadcastMode instead.
     * @deprecated
     */
    class Config_DeviceConfig_RebroadcastMode {}
}
class_exists(Config\DeviceConfig\RebroadcastMode::class);
@trigger_error('Meshtastic\Config_DeviceConfig_RebroadcastMode is deprecated and will be removed in the next major release. Use Meshtastic\Config\DeviceConfig\RebroadcastMode instead', E_USER_DEPRECATED);

