<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\NetworkConfig instead.
     * @deprecated
     */
    class Config_NetworkConfig {}
}
class_exists(Config\NetworkConfig::class);
@trigger_error('Meshtastic\Config_NetworkConfig is deprecated and will be removed in the next major release. Use Meshtastic\Config\NetworkConfig instead', E_USER_DEPRECATED);

