<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\PositionConfig\PositionFlags instead.
     * @deprecated
     */
    class Config_PositionConfig_PositionFlags {}
}
class_exists(Config\PositionConfig\PositionFlags::class);
@trigger_error('Meshtastic\Config_PositionConfig_PositionFlags is deprecated and will be removed in the next major release. Use Meshtastic\Config\PositionConfig\PositionFlags instead', E_USER_DEPRECATED);

