<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\DeviceConfig instead.
     * @deprecated
     */
    class Config_DeviceConfig {}
}
class_exists(Config\DeviceConfig::class);
@trigger_error('Meshtastic\Config_DeviceConfig is deprecated and will be removed in the next major release. Use Meshtastic\Config\DeviceConfig instead', E_USER_DEPRECATED);

