<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\SessionkeyConfig instead.
     * @deprecated
     */
    class Config_SessionkeyConfig {}
}
class_exists(Config\SessionkeyConfig::class);
@trigger_error('Meshtastic\Config_SessionkeyConfig is deprecated and will be removed in the next major release. Use Meshtastic\Config\SessionkeyConfig instead', E_USER_DEPRECATED);

