<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\BluetoothConfig\PairingMode instead.
     * @deprecated
     */
    class Config_BluetoothConfig_PairingMode {}
}
class_exists(Config\BluetoothConfig\PairingMode::class);
@trigger_error('Meshtastic\Config_BluetoothConfig_PairingMode is deprecated and will be removed in the next major release. Use Meshtastic\Config\BluetoothConfig\PairingMode instead', E_USER_DEPRECATED);

