<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\DisplayConfig\DisplayUnits instead.
     * @deprecated
     */
    class Config_DisplayConfig_DisplayUnits {}
}
class_exists(Config\DisplayConfig\DisplayUnits::class);
@trigger_error('Meshtastic\Config_DisplayConfig_DisplayUnits is deprecated and will be removed in the next major release. Use Meshtastic\Config\DisplayConfig\DisplayUnits instead', E_USER_DEPRECATED);

