<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\DisplayConfig\DisplayMode instead.
     * @deprecated
     */
    class Config_DisplayConfig_DisplayMode {}
}
class_exists(Config\DisplayConfig\DisplayMode::class);
@trigger_error('Meshtastic\Config_DisplayConfig_DisplayMode is deprecated and will be removed in the next major release. Use Meshtastic\Config\DisplayConfig\DisplayMode instead', E_USER_DEPRECATED);

