<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\DisplayConfig\CompassOrientation instead.
     * @deprecated
     */
    class Config_DisplayConfig_CompassOrientation {}
}
class_exists(Config\DisplayConfig\CompassOrientation::class);
@trigger_error('Meshtastic\Config_DisplayConfig_CompassOrientation is deprecated and will be removed in the next major release. Use Meshtastic\Config\DisplayConfig\CompassOrientation instead', E_USER_DEPRECATED);

