<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\PositionConfig\GpsMode instead.
     * @deprecated
     */
    class Config_PositionConfig_GpsMode {}
}
class_exists(Config\PositionConfig\GpsMode::class);
@trigger_error('Meshtastic\Config_PositionConfig_GpsMode is deprecated and will be removed in the next major release. Use Meshtastic\Config\PositionConfig\GpsMode instead', E_USER_DEPRECATED);

