<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\PowerConfig instead.
     * @deprecated
     */
    class Config_PowerConfig {}
}
class_exists(Config\PowerConfig::class);
@trigger_error('Meshtastic\Config_PowerConfig is deprecated and will be removed in the next major release. Use Meshtastic\Config\PowerConfig instead', E_USER_DEPRECATED);

