<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\DeviceConfig\BuzzerMode instead.
     * @deprecated
     */
    class Config_DeviceConfig_BuzzerMode {}
}
class_exists(Config\DeviceConfig\BuzzerMode::class);
@trigger_error('Meshtastic\Config_DeviceConfig_BuzzerMode is deprecated and will be removed in the next major release. Use Meshtastic\Config\DeviceConfig\BuzzerMode instead', E_USER_DEPRECATED);

