<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\DisplayConfig\OledType instead.
     * @deprecated
     */
    class Config_DisplayConfig_OledType {}
}
class_exists(Config\DisplayConfig\OledType::class);
@trigger_error('Meshtastic\Config_DisplayConfig_OledType is deprecated and will be removed in the next major release. Use Meshtastic\Config\DisplayConfig\OledType instead', E_USER_DEPRECATED);

