<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\DeviceConfig\Role instead.
     * @deprecated
     */
    class Config_DeviceConfig_Role {}
}
class_exists(Config\DeviceConfig\Role::class);
@trigger_error('Meshtastic\Config_DeviceConfig_Role is deprecated and will be removed in the next major release. Use Meshtastic\Config\DeviceConfig\Role instead', E_USER_DEPRECATED);

