<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\LoRaConfig\ModemPreset instead.
     * @deprecated
     */
    class Config_LoRaConfig_ModemPreset {}
}
class_exists(Config\LoRaConfig\ModemPreset::class);
@trigger_error('Meshtastic\Config_LoRaConfig_ModemPreset is deprecated and will be removed in the next major release. Use Meshtastic\Config\LoRaConfig\ModemPreset instead', E_USER_DEPRECATED);

