<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Config\NetworkConfig\ProtocolFlags instead.
     * @deprecated
     */
    class Config_NetworkConfig_ProtocolFlags {}
}
class_exists(Config\NetworkConfig\ProtocolFlags::class);
@trigger_error('Meshtastic\Config_NetworkConfig_ProtocolFlags is deprecated and will be removed in the next major release. Use Meshtastic\Config\NetworkConfig\ProtocolFlags instead', E_USER_DEPRECATED);

