<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/device_ui.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\DeviceUIConfig\GpsCoordinateFormat instead.
     * @deprecated
     */
    class DeviceUIConfig_GpsCoordinateFormat {}
}
class_exists(DeviceUIConfig\GpsCoordinateFormat::class);
@trigger_error('Meshtastic\DeviceUIConfig_GpsCoordinateFormat is deprecated and will be removed in the next major release. Use Meshtastic\DeviceUIConfig\GpsCoordinateFormat instead', E_USER_DEPRECATED);

