<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/remote_hardware.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\HardwareMessage\Type instead.
     * @deprecated
     */
    class HardwareMessage_Type {}
}
class_exists(HardwareMessage\Type::class);
@trigger_error('Meshtastic\HardwareMessage_Type is deprecated and will be removed in the next major release. Use Meshtastic\HardwareMessage\Type instead', E_USER_DEPRECATED);

