<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\KeyVerificationAdmin\MessageType instead.
     * @deprecated
     */
    class KeyVerificationAdmin_MessageType {}
}
class_exists(KeyVerificationAdmin\MessageType::class);
@trigger_error('Meshtastic\KeyVerificationAdmin_MessageType is deprecated and will be removed in the next major release. Use Meshtastic\KeyVerificationAdmin\MessageType instead', E_USER_DEPRECATED);

