<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\LogRecord\Level instead.
     * @deprecated
     */
    class LogRecord_Level {}
}
class_exists(LogRecord\Level::class);
@trigger_error('Meshtastic\LogRecord_Level is deprecated and will be removed in the next major release. Use Meshtastic\LogRecord\Level instead', E_USER_DEPRECATED);

