<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\MeshPacket\TransportMechanism instead.
     * @deprecated
     */
    class MeshPacket_TransportMechanism {}
}
class_exists(MeshPacket\TransportMechanism::class);
@trigger_error('Meshtastic\MeshPacket_TransportMechanism is deprecated and will be removed in the next major release. Use Meshtastic\MeshPacket\TransportMechanism instead', E_USER_DEPRECATED);

