<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\MeshPacket\Delayed instead.
     * @deprecated
     */
    class MeshPacket_Delayed {}
}
class_exists(MeshPacket\Delayed::class);
@trigger_error('Meshtastic\MeshPacket_Delayed is deprecated and will be removed in the next major release. Use Meshtastic\MeshPacket\Delayed instead', E_USER_DEPRECATED);

