<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\MeshPacket\Priority instead.
     * @deprecated
     */
    class MeshPacket_Priority {}
}
class_exists(MeshPacket\Priority::class);
@trigger_error('Meshtastic\MeshPacket_Priority is deprecated and will be removed in the next major release. Use Meshtastic\MeshPacket\Priority instead', E_USER_DEPRECATED);

