<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\RangeTestConfig instead.
     * @deprecated
     */
    class ModuleConfig_RangeTestConfig {}
}
class_exists(ModuleConfig\RangeTestConfig::class);
@trigger_error('Meshtastic\ModuleConfig_RangeTestConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\RangeTestConfig instead', E_USER_DEPRECATED);

