<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\ExternalNotificationConfig instead.
     * @deprecated
     */
    class ModuleConfig_ExternalNotificationConfig {}
}
class_exists(ModuleConfig\ExternalNotificationConfig::class);
@trigger_error('Meshtastic\ModuleConfig_ExternalNotificationConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\ExternalNotificationConfig instead', E_USER_DEPRECATED);

