<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\PaxcounterConfig instead.
     * @deprecated
     */
    class ModuleConfig_PaxcounterConfig {}
}
class_exists(ModuleConfig\PaxcounterConfig::class);
@trigger_error('Meshtastic\ModuleConfig_PaxcounterConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\PaxcounterConfig instead', E_USER_DEPRECATED);

