<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\DetectionSensorConfig instead.
     * @deprecated
     */
    class ModuleConfig_DetectionSensorConfig {}
}
class_exists(ModuleConfig\DetectionSensorConfig::class);
@trigger_error('Meshtastic\ModuleConfig_DetectionSensorConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\DetectionSensorConfig instead', E_USER_DEPRECATED);

