<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\AudioConfig instead.
     * @deprecated
     */
    class ModuleConfig_AudioConfig {}
}
class_exists(ModuleConfig\AudioConfig::class);
@trigger_error('Meshtastic\ModuleConfig_AudioConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\AudioConfig instead', E_USER_DEPRECATED);

