<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\RemoteHardwareConfig instead.
     * @deprecated
     */
    class ModuleConfig_RemoteHardwareConfig {}
}
class_exists(ModuleConfig\RemoteHardwareConfig::class);
@trigger_error('Meshtastic\ModuleConfig_RemoteHardwareConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\RemoteHardwareConfig instead', E_USER_DEPRECATED);

