<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\TelemetryConfig instead.
     * @deprecated
     */
    class ModuleConfig_TelemetryConfig {}
}
class_exists(ModuleConfig\TelemetryConfig::class);
@trigger_error('Meshtastic\ModuleConfig_TelemetryConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\TelemetryConfig instead', E_USER_DEPRECATED);

