<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\SerialConfig\Serial_Mode instead.
     * @deprecated
     */
    class ModuleConfig_SerialConfig_Serial_Mode {}
}
class_exists(ModuleConfig\SerialConfig\Serial_Mode::class);
@trigger_error('Meshtastic\ModuleConfig_SerialConfig_Serial_Mode is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\SerialConfig\Serial_Mode instead', E_USER_DEPRECATED);

