<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\StoreForwardConfig instead.
     * @deprecated
     */
    class ModuleConfig_StoreForwardConfig {}
}
class_exists(ModuleConfig\StoreForwardConfig::class);
@trigger_error('Meshtastic\ModuleConfig_StoreForwardConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\StoreForwardConfig instead', E_USER_DEPRECATED);

