<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\CannedMessageConfig\InputEventChar instead.
     * @deprecated
     */
    class ModuleConfig_CannedMessageConfig_InputEventChar {}
}
class_exists(ModuleConfig\CannedMessageConfig\InputEventChar::class);
@trigger_error('Meshtastic\ModuleConfig_CannedMessageConfig_InputEventChar is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\CannedMessageConfig\InputEventChar instead', E_USER_DEPRECATED);

