<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\SerialConfig instead.
     * @deprecated
     */
    class ModuleConfig_SerialConfig {}
}
class_exists(ModuleConfig\SerialConfig::class);
@trigger_error('Meshtastic\ModuleConfig_SerialConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\SerialConfig instead', E_USER_DEPRECATED);

