<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\StatusMessageConfig instead.
     * @deprecated
     */
    class ModuleConfig_StatusMessageConfig {}
}
class_exists(ModuleConfig\StatusMessageConfig::class);
@trigger_error('Meshtastic\ModuleConfig_StatusMessageConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\StatusMessageConfig instead', E_USER_DEPRECATED);

