<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\CannedMessageConfig instead.
     * @deprecated
     */
    class ModuleConfig_CannedMessageConfig {}
}
class_exists(ModuleConfig\CannedMessageConfig::class);
@trigger_error('Meshtastic\ModuleConfig_CannedMessageConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\CannedMessageConfig instead', E_USER_DEPRECATED);

