<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\MapReportSettings instead.
     * @deprecated
     */
    class ModuleConfig_MapReportSettings {}
}
class_exists(ModuleConfig\MapReportSettings::class);
@trigger_error('Meshtastic\ModuleConfig_MapReportSettings is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\MapReportSettings instead', E_USER_DEPRECATED);

