<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\MQTTConfig instead.
     * @deprecated
     */
    class ModuleConfig_MQTTConfig {}
}
class_exists(ModuleConfig\MQTTConfig::class);
@trigger_error('Meshtastic\ModuleConfig_MQTTConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\MQTTConfig instead', E_USER_DEPRECATED);

