<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\AmbientLightingConfig instead.
     * @deprecated
     */
    class ModuleConfig_AmbientLightingConfig {}
}
class_exists(ModuleConfig\AmbientLightingConfig::class);
@trigger_error('Meshtastic\ModuleConfig_AmbientLightingConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\AmbientLightingConfig instead', E_USER_DEPRECATED);

