<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\AudioConfig\Audio_Baud instead.
     * @deprecated
     */
    class ModuleConfig_AudioConfig_Audio_Baud {}
}
class_exists(ModuleConfig\AudioConfig\Audio_Baud::class);
@trigger_error('Meshtastic\ModuleConfig_AudioConfig_Audio_Baud is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\AudioConfig\Audio_Baud instead', E_USER_DEPRECATED);

