<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\TrafficManagementConfig instead.
     * @deprecated
     */
    class ModuleConfig_TrafficManagementConfig {}
}
class_exists(ModuleConfig\TrafficManagementConfig::class);
@trigger_error('Meshtastic\ModuleConfig_TrafficManagementConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\TrafficManagementConfig instead', E_USER_DEPRECATED);

