<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\DetectionSensorConfig\TriggerType instead.
     * @deprecated
     */
    class ModuleConfig_DetectionSensorConfig_TriggerType {}
}
class_exists(ModuleConfig\DetectionSensorConfig\TriggerType::class);
@trigger_error('Meshtastic\ModuleConfig_DetectionSensorConfig_TriggerType is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\DetectionSensorConfig\TriggerType instead', E_USER_DEPRECATED);

