<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/module_config.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\ModuleConfig\NeighborInfoConfig instead.
     * @deprecated
     */
    class ModuleConfig_NeighborInfoConfig {}
}
class_exists(ModuleConfig\NeighborInfoConfig::class);
@trigger_error('Meshtastic\ModuleConfig_NeighborInfoConfig is deprecated and will be removed in the next major release. Use Meshtastic\ModuleConfig\NeighborInfoConfig instead', E_USER_DEPRECATED);

