<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Position\AltSource instead.
     * @deprecated
     */
    class Position_AltSource {}
}
class_exists(Position\AltSource::class);
@trigger_error('Meshtastic\Position_AltSource is deprecated and will be removed in the next major release. Use Meshtastic\Position\AltSource instead', E_USER_DEPRECATED);

