<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Position\LocSource instead.
     * @deprecated
     */
    class Position_LocSource {}
}
class_exists(Position\LocSource::class);
@trigger_error('Meshtastic\Position_LocSource is deprecated and will be removed in the next major release. Use Meshtastic\Position\LocSource instead', E_USER_DEPRECATED);

