<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/powermon.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\PowerMon\State instead.
     * @deprecated
     */
    class PowerMon_State {}
}
class_exists(PowerMon\State::class);
@trigger_error('Meshtastic\PowerMon_State is deprecated and will be removed in the next major release. Use Meshtastic\PowerMon\State instead', E_USER_DEPRECATED);

