<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/powermon.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\PowerStressMessage\Opcode instead.
     * @deprecated
     */
    class PowerStressMessage_Opcode {}
}
class_exists(PowerStressMessage\Opcode::class);
@trigger_error('Meshtastic\PowerStressMessage_Opcode is deprecated and will be removed in the next major release. Use Meshtastic\PowerStressMessage\Opcode instead', E_USER_DEPRECATED);

