<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\Routing\Error instead.
     * @deprecated
     */
    class Routing_Error {}
}
class_exists(Routing\Error::class);
@trigger_error('Meshtastic\Routing_Error is deprecated and will be removed in the next major release. Use Meshtastic\Routing\Error instead', E_USER_DEPRECATED);

