<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\StoreForwardPlusPlus\SFPP_message_type instead.
     * @deprecated
     */
    class StoreForwardPlusPlus_SFPP_message_type {}
}
class_exists(StoreForwardPlusPlus\SFPP_message_type::class);
@trigger_error('Meshtastic\StoreForwardPlusPlus_SFPP_message_type is deprecated and will be removed in the next major release. Use Meshtastic\StoreForwardPlusPlus\SFPP_message_type instead', E_USER_DEPRECATED);

