<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/storeforward.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\StoreAndForward\Heartbeat instead.
     * @deprecated
     */
    class StoreAndForward_Heartbeat {}
}
class_exists(StoreAndForward\Heartbeat::class);
@trigger_error('Meshtastic\StoreAndForward_Heartbeat is deprecated and will be removed in the next major release. Use Meshtastic\StoreAndForward\Heartbeat instead', E_USER_DEPRECATED);

