<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/storeforward.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\StoreAndForward\Statistics instead.
     * @deprecated
     */
    class StoreAndForward_Statistics {}
}
class_exists(StoreAndForward\Statistics::class);
@trigger_error('Meshtastic\StoreAndForward_Statistics is deprecated and will be removed in the next major release. Use Meshtastic\StoreAndForward\Statistics instead', E_USER_DEPRECATED);

