<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/storeforward.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\StoreAndForward\RequestResponse instead.
     * @deprecated
     */
    class StoreAndForward_RequestResponse {}
}
class_exists(StoreAndForward\RequestResponse::class);
@trigger_error('Meshtastic\StoreAndForward_RequestResponse is deprecated and will be removed in the next major release. Use Meshtastic\StoreAndForward\RequestResponse instead', E_USER_DEPRECATED);

