<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/storeforward.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\StoreAndForward\History instead.
     * @deprecated
     */
    class StoreAndForward_History {}
}
class_exists(StoreAndForward\History::class);
@trigger_error('Meshtastic\StoreAndForward_History is deprecated and will be removed in the next major release. Use Meshtastic\StoreAndForward\History instead', E_USER_DEPRECATED);

