<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/xmodem.proto

namespace Meshtastic;

if (false) {
    /**
     * This class is deprecated. Use Meshtastic\XModem\Control instead.
     * @deprecated
     */
    class XModem_Control {}
}
class_exists(XModem\Control::class);
@trigger_error('Meshtastic\XModem_Control is deprecated and will be removed in the next major release. Use Meshtastic\XModem\Control instead', E_USER_DEPRECATED);

